#!/bin/bash

set -e # fail on error

# Use the local sde command.
SDE='node ../sde.js'
$SDE -v &>/dev/null
if [[ $? -ne 0 ]]; then
  echo 'SDEverywhere is not installed.'
  echo 'Run "npm install" in the top directory to install it locally.'
  exit 1
fi

function test {
  MODEL=$1
  echo "Testing the $MODEL model"
  MODEL_DIR=../../models/$MODEL
  $SDE clean --modeldir $MODEL_DIR
  if [[ -f $MODEL_DIR/spec.json ]]; then
    TEST_ARGS="--spec $MODEL_DIR/spec.json"
  else
    TEST_ARGS=
  fi
  $SDE test $TEST_ARGS -p 1e-4 $MODEL_DIR/$MODEL
  $SDE clean --modeldir $MODEL_DIR
  echo
}

if [[ -n $1 ]]; then
  # Test the given model against saved Vensim data.
  test $1
else
  # Test each model against saved Vensim data.
  for m in $(ls ../../models); do
    test $m
  done
fi
