#!/usr/bin/env sh
for MODEL in $(ls ../../models); do
  echo "testing the $MODEL model"
  node ../sde.js clean ../../models/$MODEL/$MODEL
  node ../sde.js test ../../models/$MODEL/$MODEL -p 1e-4
  node ../sde.js clean ../../models/$MODEL/$MODEL
done
