// Copyright (c) 2022 Climate Interactive / New Venture Fund

export interface ImplVarSpec {
  /** The variable identifier (as generated by the SDEverywhere compiler). */
  varId: string
  /** The variable name (as used in the modeling tool). */
  varName: string
}

export interface ModelImplSpec {}

/**
 * Gather the set of internal/implementation variables used in this version of the model.
 */
export function getImplVars(implVarSpecs: ImplVarSpec[]): Map<VarId, ImplVar> {
  const implVars: Map<VarId, ImplVar> = new Map()
  return implVars
}
