// Copyright (c) 2026 Climate Interactive / New Venture Fund

/**
 * A variable name as used in the modeling tool, for example `Some Var[DimA]` as
 * used in a Vensim model.
 */
export type VarName = string

/**
 * A variable identifier in the canonical format used internally by SDEverywhere,
 * for example `_some_var`.  These are derived from a `VarName` by lowercasing the
 * name and replacing special characters with underscores.
 */
export type VarId = string

/**
 * A dimension (subscript range) identifier in the canonical format used internally
 * by SDEverywhere, for example `_dima`.
 */
export type DimId = string

/**
 * Describes a `dat` file that provides data for exogenous data variables in the model.
 *
 * This can either be:
 *   - a plain file name (relative to the model directory), for example `data.dat`, or
 *   - an object with a single key/value pair, where the key is a prefix that is
 *     prepended to each variable name read from the file, and the value is the file
 *     name, for example `{ "prefix ": "data.dat" }`.
 */
export type DatFileSpec = string | { [varNamePrefix: string]: string }

/**
 * Describes a model (e.g., a Vensim mdl file) and the input/output variables that
 * should be included in the model generated by SDEverywhere.
 *
 * This is the type of the object that is parsed from a `spec.json` file (as passed
 * to the `sde generate` command using the `--spec` argument) and that is accepted by
 * the `parseAndGenerate` function.
 *
 * All properties are optional.  If neither `inputVarNames` nor `outputVarNames` is
 * provided, the generated model will include all variables from the model and will not
 * allow any inputs to be set at runtime.
 */
export interface ModelSpec {
  /**
   * The input variables for the model, using the variable names as they appear in
   * the modeling tool.
   *
   * When this is provided, only the listed variables can be set at runtime, and any
   * variables that are not needed to compute the configured `outputVarNames` will be
   * pruned from the generated model.
   */
  inputVarNames?: VarName[]

  /**
   * The output variables for the model, using the variable names as they appear in
   * the modeling tool.
   *
   * It is customary to include `Time` as the first output variable.
   *
   * When this is provided, only the listed variables (plus the variables needed to
   * compute them) will be included in the generated model.
   */
  outputVarNames?: VarName[]

  /**
   * The `dat` files that provide the data for exogenous data variables in the model.
   *
   * Each entry is resolved relative to the model directory (i.e., the directory that
   * is passed using the `--datadir` argument, which defaults to the directory that
   * contains the model file).
   */
  datFiles?: DatFileSpec[]

  /**
   * The mapping of data tag to Excel workbook file name, used to resolve the data for
   * `GET DIRECT DATA`, `GET DIRECT CONSTANTS`, and `GET DIRECT LOOKUPS` calls in the
   * model.
   *
   * Each key is the tag that appears in the model equation (for example, `?data`), and
   * each value is the name of an `xlsx` file that is resolved relative to the model
   * directory.
   */
  directData?: { [dataTag: string]: string }

  /**
   * The mapping of dimension name to family name, used when SDEverywhere cannot infer
   * the family for a dimension from the model alone.
   *
   * Both the keys and the values use the dimension names as they appear in the modeling
   * tool (they are converted to canonical form when the spec file is read).
   */
  dimensionFamilies?: { [dimName: string]: string }

  /**
   * The mapping of variable identifier to the dimension(s) on which that variable should
   * be separated into one variable instance per subscript.
   *
   * Separating a variable is sometimes necessary to break a dependency cycle that would
   * otherwise prevent the model from being evaluated.  Each value can be either a single
   * dimension identifier or an array of dimension identifiers.
   */
  specialSeparationDims?: { [varId: VarId]: DimId | DimId[] }

  /**
   * The dimensions for which all variables should be separated into one variable instance
   * per subscript.
   *
   * This is a convenience alternative to `specialSeparationDims` that avoids the need to
   * list each affected variable.  Each entry can be either a single dimension identifier
   * or an array of dimension identifiers; a variable is separated only if every dimension
   * in the entry appears on the left-hand side of its equation.
   */
  separateAllVarsWithDims?: (DimId | DimId[])[]

  /**
   * Whether to bundle a model listing with the generated model.
   *
   * If undefined, defaults to false.
   *
   * When this is true, a model listing will be bundled with the generated model to allow
   * the `runtime` package to resolve variables that are referenced by name or identifier.
   * This listing will increase the size of the generated model, so it is recommended to
   * set this to true only if it is needed.
   */
  bundleListing?: boolean

  /**
   * Whether to allow constants to be overridden at runtime using `setConstant`.
   *
   * If undefined or false, the generated model will implement `setConstant` as a no-op,
   * meaning that constants cannot be overridden at runtime.
   *
   * If true, all constants in the generated model will be available to be overridden.
   *
   * If an array is provided, only those variable names in the array will be available to
   * be overridden.
   */
  customConstants?: boolean | VarName[]

  /**
   * Whether to allow lookups to be overridden at runtime using `setLookup`.
   *
   * If undefined or false, the generated model will implement `setLookup` as a no-op,
   * meaning that lookups cannot be overridden at runtime.
   *
   * If true, all lookups in the generated model will be available to be overridden.
   *
   * If an array is provided, only those variable names in the array will be available to
   * be overridden.
   */
  customLookups?: boolean | VarName[]

  /**
   * Whether to allow for capturing the data for arbitrary variables at runtime (including
   * variables that are not configured in the `outputVarNames` array).
   *
   * If undefined or false, the generated model will implement `storeOutput` as a no-op,
   * meaning that the data for arbitrary variables cannot be captured at runtime.
   *
   * If true, all variables in the generated model will be available to be captured at
   * runtime.
   *
   * If an array is provided, only those variable names in the array will be available to
   * be captured at runtime.
   */
  customOutputs?: boolean | VarName[]

  /**
   * The `dat` files that provide the data for exogenous data variables in the model.
   *
   * @deprecated Use `datFiles` instead.  This property is still honored (but is ignored
   * if `datFiles` is also provided) and will be removed in a future release.
   */
  externalDatfiles?: DatFileSpec[]

  /**
   * A descriptive name for the model.
   *
   * @deprecated This property is ignored by SDEverywhere and will be removed in a
   * future release.
   */
  name?: string

  /**
   * The input variable identifiers for the model, in canonical form.
   *
   * @hidden This is derived from `inputVarNames` while the model is being read, and is
   * not intended to be set in a `spec.json` file.
   */
  inputVars?: VarId[]

  /**
   * The output variable identifiers for the model, in canonical form.
   *
   * @hidden This is derived from `outputVarNames` while the model is being read, and is
   * not intended to be set in a `spec.json` file.
   */
  outputVars?: VarId[]
}

/**
 * Normalize the given model spec so that only the preferred property names need to be
 * consulted afterwards.
 *
 * For each property that has been renamed over time, this copies the value from the
 * deprecated property to the preferred one, unless the preferred property is already
 * defined (in which case the preferred one wins).  The deprecated properties are left
 * in place.
 *
 * Note that the given spec object is modified in place (and returned for convenience).
 * This function is idempotent, so it is safe to call it more than once on the same spec.
 *
 * @param spec The model spec to normalize, or undefined.
 * @returns The same spec object that was provided.
 */
export function normalizeModelSpec<T extends ModelSpec | undefined>(spec: T): T
