// Copyright (c) 2022 Climate Interactive / New Venture Fund

import type { ConfigContext } from './context'
import { sdeNameForVensimVarName } from './var-names'

/**
 * Write the `model-spec.ts` file used by the core package to initialize the model.
 */
export function writeModelSpec(context: ConfigContext, dstDir: string): void {
  // Create ordered arrays of inputs and outputs
  const inputVarIds = context.getOrderedInputs().map(i => sdeNameForVensimVarName(i.varName))
  const outputVarIds = context.getOrderedOutputs().map(o => sdeNameForVensimVarName(o.varName))

  // Generate the `model-spec.ts` file
  let tsContent = ''
  function emit(s: string): void {
    tsContent += s + '\n'
  }

  emit('// This file is generated by `@sdeverywhere/plugin-config`; do not edit manually!')
  emit(`export const inputVarIds: string[] = ${JSON.stringify(inputVarIds, null, 2)}`)
  emit(`export const outputVarIds: string[] = ${JSON.stringify(outputVarIds, null, 2)}`)

  // Write the `model-spec.ts` file to the staged directory
  context.writeStagedFile('model', dstDir, 'model-spec.ts', tsContent)
}
