#!/usr/bin/env sh
antlr4='java -jar /usr/local/lib/antlr-4.7-complete.jar'
grun='java org.antlr.v4.gui.TestRig'
if [ "$#" = "0" ]; then
  echo "usage: lex [-g] mdl-filename"
  echo "-g generates the lexer and parser before running the lexer"
  exit
fi
if [ "$1" = "-g" ]; then
  rm Model*.java *.class *.tokens >&/dev/null
  $antlr4 -no-visitor -no-listener Model.g4
  javac *.java
  shift
fi
cat Model.tokens
$grun Model model -tokens $1
