#!/usr/bin/env sh
antlr4='java -jar /usr/local/lib/antlr-4.5-complete.jar'
grun='java org.antlr.v4.runtime.misc.TestRig'
if [ "$#" = "0" ]; then
  echo "usage: tree [-g] mdl-filename"
  echo "-g generates the lexer and grammar"
  exit
fi
if [ "$1" = "-g" ]; then
  rm Model*.java *.class *.tokens >&/dev/null
  $antlr4 -no-visitor -no-listener Model.g4
  javac *.java
  shift
fi
$grun Model model -tree $1 >~/tmp/x
babel-node sdetree.js -f ~/tmp/x
