app:
  title: {application title string}
  logo: {optional filename string of an app logo image}
  version: {version number string}
  datfiles: {optional array of Vensim DAT filename strings giving external data variables}
  removalKeys: {optional array of strings to search for in equations we want to remove in preprocessing}
  help_url: {optional URL string of an online help file}
  colors:
    color_1: '#0072b2' # blue
    color_2: '#d33700' # red
    color_3: '#53bb37' # green
    color_4: '#a7a9ac' # gray
    color_5: '#000000' # black
  initial_view: {first level view title} > {second level view title}
  track_sliders: {boolean indicating whether to run the model as a slider is moved}
  sliders:
    {Vensim variable name string}:
      label: {slider label string}
      units: {units string}
      format: {slider number format string, see http://numbrojs.com/}
      value: {number giving the initial value of the slider variable}
      min: {number giving the minimum value of the slider range}
      max: {number giving the maximum value of the slider range}
      step: {number giving the slider step interval}
views:
  - title: {first level menu title string}
    views:
      - title: {view title string}
        graphs:
          - title: {graph title string}
            x_axis:
              min: {number giving the x axis minimum value}
              max: {number giving the x axis maximum value}
            y_axis:
              units: {y axis units label string}
              format: {y axis label number format string, see http://numbrojs.com/}
              min: {number giving the y axis minimum value}
              max: {number giving the y axis maximum value}
            plots:
              - name: {Vensim variable name string to plot}
                label: {graph legend string}
                color: {name string of the color for the graph line from app.colors above}
                style: {graph line style string, either line, area, or thinline}
    sliders:
