// Copyright (c) 2022 Climate Interactive / New Venture Fund

import { readFileSync } from 'fs'
import { basename, dirname, join as joinPath } from 'path'

import { build } from 'vite'

import type { BuildContext, Plugin } from '@sdeverywhere/build'

import type { WorkerPluginOptions } from './options'
import { createViteConfig } from './vite-config'

export function workerPlugin(options?: WorkerPluginOptions): Plugin {
  return new WorkerPlugin(options)
}

class WorkerPlugin implements Plugin {
  constructor(private readonly options?: WorkerPluginOptions) {}

  async postGenerate(context: BuildContext): Promise<boolean> {
    const log = context.log
    log('info', 'Building worker')

    // Locate the generated model file in the staged directory.  Note that this
    // relies on the `build` package writing the JS model (or the `plugin-wasm`
    // package writing the Wasm model) to a file called `generated-model.js`
    // in the `staged/model` directory.
    // TODO: Allow for customizing the file name/path
    const prepDir = context.config.prepDir
    const srcDir = 'model'
    const stagedModelDir = joinPath(prepDir, 'staged', srcDir)
    const inModelJsFile = 'generated-model.js'
    const outWorkerJsFile = 'worker.js'

    // If neither `outputPaths` nor `outputSourceModulePaths` is defined, write the
    // `worker.js` to the prep dir
    const outputSourceModulePaths = this.options?.outputSourceModulePaths || []
    let outputPaths = this.options?.outputPaths
    if (outputPaths === undefined) {
      outputPaths = outputSourceModulePaths.length > 0 ? [] : [joinPath(prepDir, outWorkerJsFile)]
    }

    // Add staged file entries; this will cause the generated worker to be copied
    // to the configured output paths during the "copy staged files" step
    // TODO: This assumes that other plugins that use the generated worker files
    // will run after the "copy staged files" step.  There might be use cases
    // where a plugin needs access to these in `postGenerate`, in which case the
    // files will not have been copied already.  Need to reconsider the ordering
    // of plugins and the "copy staged files" step(s).
    for (const outputPath of outputPaths) {
      const dstDir = dirname(outputPath)
      const dstFile = basename(outputPath)
      context.prepareStagedFile(srcDir, outWorkerJsFile, dstDir, dstFile)
    }

    // Build the worker and write generated file to the `staged/model` directory
    const viteConfig = createViteConfig(stagedModelDir, inModelJsFile, outWorkerJsFile)
    await build(viteConfig)

    // Write a module that exports the worker source code (as a string) for each of the
    // configured `outputSourceModulePaths`
    if (outputSourceModulePaths.length > 0) {
      const workerJs = readFileSync(joinPath(stagedModelDir, outWorkerJsFile), 'utf8')
      const moduleContent = `\
// This file is generated by @sdeverywhere/plugin-worker; do not edit.
export default ${JSON.stringify(workerJs)}
`
      for (const outputPath of outputSourceModulePaths) {
        context.writeStagedFile(srcDir, dirname(outputPath), basename(outputPath), moduleContent)
      }
    }

    // log('info', 'Done!')

    return true
  }
}
