#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJ_DIR=$SCRIPT_DIR/..

set -e # fail on error
set -x # include all commands in logs

cd "$PROJ_DIR"

# Build the subset of packages that are required for running the JS-level
# integration tests
pnpm -F build build
pnpm -F plugin-wasm build
pnpm -F plugin-worker build
pnpm -F runtime build
pnpm -F runtime-async build

# Run the JS-level integration tests that exercise the build and runtime packages
pnpm run test:js-int

# Fail the build if there are any untracked or modified files.  This usually
# only occurs if the typedoc-generated docs need updating after any API
# changes.  (We currently keep the generated API docs as tracked files in
# the repo, and updating them is a manual step.)
set +e
set +x
if [[ -n "$(git status --porcelain)" ]]; then
echo
  echo "ERROR: There are untracked or modified files reported by git"
  echo
  git status
  echo
  exit 1
fi
