// Copyright (c) 2025 Climate Interactive / New Venture Fund

/**
 * Describes a build product that will be copied to the deployment directory.
 */
export interface BuildProduct {
  /**
   * The name of the build product as used in the link in the top-level index page.  If undefined,
   * no link will be included in the top-level index page.
   */
  displayName?: string

  /** The source path of the build product, relative to the project root directory (`rootDir`). */
  srcPath: string

  /** The destination path of the build product, relative to the deployment directory (`deployDir`). */
  dstPath: string
}

/**
 * The options that control the deployment process.
 */
export interface DeployPluginOptions {
  /**
   * The base URL for the published project.  This is used for determining the URLs
   * for remote bundle files used by model-check and for other purposes.
   *
   * By default, the plugin assumes deployment to GitHub Pages, so if this property is
   * undefined, the following default template will be used:
   * ```
   *   baseUrl: 'https://{GH_USERNAME_OR_ORG}.github.io/{GH_REPO_NAME}'
   * ```
   *
   * For example, if your GitHub username is "sdmodeler123", and your GitHub repository
   * is called "my-sd-model", `baseUrl` will be set as follows:
   * ```
   *   baseUrl: 'https://sdmodeler123.github.io/my-sd-model'
   * ```
   *
   * IMPORTANT: If you set up GitHub Pages to use a custom domain, be sure to update
   * this variable to use that custom domain, otherwise model-check may fail to load
   * bundles due to cross origin redirect issues, for example:
   * ```
   *   baseUrl: 'https://sdmodeler123.com/my-sd-model'
   * ```
   *
   * If you use a different host/server (AWS, GitLab, etc) or publish to a different
   * directory structure, you can update this variable to suit your needs, for example:
   * ```
   *   baseUrl: 'https://sdmodeler123.com/projects/my-model'
   * ```
   */
  baseUrl?: string

  /**
   * The path of the directory to which the build products will be copied.
   * If undefined, defaults to the "deploy" directory under the configured
   * project `prepDir`.  The plugin will create this directory if it does not
   * exist.
   *
   * This directory is ephemeral and should be listed in your `.gitignore` file.
   */
  deployDir?: string

  /**
   * The build products that will be copied to the `deployDir` directory.
   * If undefined, defaults to the following build products that are typically
   * generated by the build process (if any of these are not available, the
   * plugin will skip copying them):
   * - The app: `packages/app/public -> ${deployDir}/app`
   * - The model-check bundle: `sde-prep/check-bundle.js -> ${deployDir}/extras/check-bundle.js`
   * - The model-check report: `sde-prep/check-report -> ${deployDir}/extras/check-compare-to-base`
   *
   * The keys of the record should be a short name for the build product, used in the `index.json`
   * file that is generated by the plugin.
   */
  products?: Record<string, BuildProduct>
}

/**
 * @hidden For internal use only.
 */
export interface ResolvedPluginOptions {
  /** The resolved base URL, or undefined if the default repository URL cannot be determined. */
  baseUrl?: string

  /** The absolute path to the deploy directory. */
  deployDir: string

  /** The resolved build products. */
  products: Record<string, BuildProduct>

  /** Whether `products` is the default set of build products. */
  defaultProducts: boolean
}
