#!/usr/bin/env sh
function usage {
  echo 'usage: sdebuild <model-name>'
  echo 'Set the SDE_HOME environment variable to the SDEverywhere directory name.'
  echo 'For example: export SDE_HOME=$HOME/Projects/SDEverywhere'
  echo 'This script assumes that each model is in a directory under $SDE_HOME/models'
  echo 'with the same name as the MDL file basename.'
  exit 1
}
if [[ -z $SDE_HOME ]]; then usage; fi
if [[ -z $1 ]]; then usage; fi
if [[ ! -d $SDE_HOME ]]; then usage; fi
if [[ ! -d $SDE_HOME/models ]]; then usage; fi
if [[ ! -d $SDE_HOME/tools ]]; then usage; fi
if [[ ! -d $SDE_HOME/build ]]; then mkdir $SDE_HOME/build; fi
# SDE=sde
SDE="node ../src/sde.js"
MDL_NAME=$1
MDL_PATH=$SDE_HOME/models/$MDL_NAME
# Generate a C model in the build directory from a Vensim model in the models directory.
$SDE generate $MDL_PATH/$MDL_NAME.mdl >$SDE_HOME/build/$MDL_NAME.c
# Compile the C code into an executable in the build directory.
$SDE_HOME/tools/sdecc $MDL_NAME
ls -l $SDE_HOME/build/$MDL_NAME
