#!/usr/bin/env sh
function usage {
  echo 'usage: sdetest <model-name> [precision]'
  echo 'Set the SDE_HOME environment variable to the SDEverywhere directory name.'
  echo 'For example: export SDE_HOME=$HOME/Projects/SDEverywhere'
  echo 'This script assumes that each model is in a directory under $SDE_HOME/models'
  echo 'with the same name as the MDL file basename.'
  echo 'First run the model in 64-bit Vensim and export the run in DAT format to the'
  echo '{model-name}.dat file.'
  exit 1
}
if [[ -z $SDE_HOME ]]; then usage; fi
if [[ -z $1 ]]; then usage; fi
if [[ ! -d $SDE_HOME ]]; then usage; fi
if [[ ! -d $SDE_HOME/models ]]; then usage; fi
if [[ ! -d $SDE_HOME/tools ]]; then usage; fi
if [[ ! -d $SDE_HOME/build ]]; then mkdir $SDE_HOME/build; fi
# SDE=sde
SDE="node ../src/sde.js"
MDL_NAME=$1
MDL_PATH=$SDE_HOME/models/$MDL_NAME
# Generate a C model in the build directory from a Vensim model in the models directory.
$SDE generate $MDL_PATH/$MDL_NAME.mdl >$SDE_HOME/build/$MDL_NAME.c
# Compile the C code into an executable in the build directory.
$SDE_HOME/tools/sdecc $MDL_NAME
# Run the executable and capture output into a text file.
$SDE_HOME/build/$MDL_NAME >$SDE_HOME/build/$MDL_NAME.txt
# Convert the text file from TSV format into Vensim dat format.
$SDE log $SDE_HOME/build/$MDL_NAME.txt --dat >$SDE_HOME/build/x
mv $SDE_HOME/build/x $SDE_HOME/build/$MDL_NAME.txt
# Compare the output to a dat file saved in Vensim, with optional parameters passed through.
$SDE compare $MDL_PATH/$MDL_NAME.dat $SDE_HOME/build/$MDL_NAME.txt $2 $3
