#!/usr/bin/env sh
function usage {
  echo 'usage: sdetestall'
  echo 'Set the SDE_HOME environment variable to the SDEverywhere directory name.'
  echo 'For example: export SDE_HOME=$HOME/Projects/SDEverywhere'
  echo 'This script assumes that each model is in a directory under $SDE_HOME/models'
  echo 'with the same name as the MDL file basename.'
  exit 1
}
if [[ -z $SDE_HOME ]]; then usage; fi
if [[ ! -d $SDE_HOME ]]; then usage; fi
if [[ ! -d $SDE_HOME/tools ]]; then usage; fi
echo 'testing the active_initial model'
$SDE_HOME/tools/sdetest active_initial
echo 'testing the arrays model'
$SDE_HOME/tools/sdetest arrays
echo 'testing the delay model'
$SDE_HOME/tools/sdetest delay
echo 'testing the delay3 model'
$SDE_HOME/tools/sdetest delay3
echo 'testing the index model'
$SDE_HOME/tools/sdetest index
echo 'testing the initial model'
$SDE_HOME/tools/sdetest initial --precision 0.0001
echo 'testing the interleaved model'
$SDE_HOME/tools/sdetest interleaved
echo 'testing the lookup model'
$SDE_HOME/tools/sdetest lookup
echo 'testing the lotka model'
$SDE_HOME/tools/sdetest lotka
echo 'testing the mapping model'
$SDE_HOME/tools/sdetest mapping
echo 'testing the ref model'
$SDE_HOME/tools/sdetest ref
echo 'testing the subscript model'
$SDE_HOME/tools/sdetest subscript
echo 'testing the sum model'
$SDE_HOME/tools/sdetest sum
echo 'testing the smooth model'
$SDE_HOME/tools/sdetest smooth
echo 'testing the smooth3 model'
$SDE_HOME/tools/sdetest smooth3
echo 'testing the vector model'
$SDE_HOME/tools/sdetest vector
