const path = require('path')
const sh = require('shelljs')
const { modelPathProps, buildDir } = require('./Helpers')

let command = 'clean [options]'
let describe = 'clean out the build, output, and html directories for a model'
let builder = {
  modeldir: {
    describe: 'model directory',
    type: 'string',
    alias: 'm'
  }
}
let handler = argv => {
  clean(argv)
}
let clean = (opts) => {
  // Remove the directories generated by SDEverywhere.
  // Default to the current directory if no model directory is given.
  let buildDirname = path.join(opts.modeldir || '.', 'build')
  let outputDirname = path.join(opts.modeldir || '.', 'output')
  let htmlDirname = path.join(opts.modeldir || '.', 'html')
  let silentState = sh.config.silent
  sh.config.silent = true
  sh.rm('-r', buildDirname)
  sh.rm('-r', outputDirname)
  sh.rm('-r', htmlDirname)
  sh.config.silent = silentState
}
module.exports = {
  command,
  describe,
  builder,
  handler,
  clean
}
