// Copyright (c) 2022 Climate Interactive / New Venture Fund

/**
 * Describes a bundle used by model-check.
 *
 * If `path` is defined, model-check will load that local JS bundle file.
 *
 * If `path` is undefined, but `url` is defined, model-check will load the
 * remote bundle file at that URL.
 *
 * If both `path` and `url` are undefined, model-check will load the latest
 * `check-bundle.js` generated by the build process.
 */
export interface CheckBundle {
  /** The name of the bundle as displayed in the report (this is typically a branch name). */
  name: string

  /** The absolute path to the local JS bundle file. */
  path?: string

  /** The URL of the remote bundle file. */
  url?: string
}

/**
 * The options that control how the model-check report is generated or served.
 */
export interface CheckPluginOptions {
  /**
   * The baseline bundle, i.e., the "left" bundle used in comparisons.
   *
   * If `baseline` is undefined, no comparison tests will be run.
   */
  baseline?: CheckBundle

  /**
   * The current bundle, i.e., the bundle that is being developed and checked.
   *
   * This will be the "right" bundle that is compared to the "left" (baseline)
   * bundle, if `baseline` is defined.  If `baseline` is undefined, no
   * comparison tests will be run, but check tests will still be run using
   * the `current` bundle.
   *
   * If `current` is undefined, the latest `check-bundle.js` generated by
   * the build process will be used as the default `current` bundle, with
   * `name` set to "current".
   */
  current?: CheckBundle

  // /**
  //  * The absolute path to the directory where local bundles are stored for use
  //  * in local development mode.  If undefined, the bundles will be loaded from
  //  * the `bundles` directory in the project root directory.
  //  *
  //  * This value is only used in "development" mode and is ignored in "production"
  //  * mode (since only the configured `baseline` and `current` bundles are used
  //  * in that case).
  //  */
  // localBundlesPath?: string

  /**
   * The URL to a JSON file containing the list of remote bundles that will be available
   * in local development mode.  The JSON file is expected to contain an array of
   * `BundleLocation` objects.  If undefined, only local bundles will be available.
   *
   * This value is only used in "development" mode and is ignored in "production"
   * mode (since only the configured `baseline` and `current` bundles are used
   * in that case).
   */
  remoteBundlesUrl?: string

  /**
   * A custom function for fetching remote bundle files.  This allows for customizing
   * the fetch operation, such as adding authentication headers or other custom logic.
   *
   * If undefined, a default fetch implementation will be used.
   *
   * @param url The URL of the remote bundle file to fetch.
   * @returns The bundle source code as a string.
   */
  fetchRemoteBundle?: (url: string) => Promise<string>

  /**
   * The absolute path to the JS file containing the test configuration.  If undefined,
   * a default test configuration will be used.
   */
  testConfigPath?: string

  /**
   * The absolute path to the directory where the report will be written.  If undefined,
   * the report will be written to the configured `prepDir`.
   */
  reportPath?: string

  /**
   * The port used for the local dev server (defaults to 8081).
   */
  serverPort?: number
}
